Add wrap function <AVFilterGraph::get_filter> to call ffi::avfilter_graph_get_filter
larksuite/rsmpeg pull request #61
Opened 2021-08-05 08:07 UTC by imxood

2021-08-05 08:09 UTC, imxood commented
It run well~

![image](https://user-images.githubusercontent.com/14890680/128315236-b8c58630-ad8b-47f4-aa28-eaf1dffea4eb.png)

2021-08-05 08:20 UTC, imxood commented
本来是高清视频, 但是现在这个清晰度太差, 不太清楚需要设置什么参数, 在我不使用filter, 只处理 decode->encode的时候, 效果也是一样不清晰, 所以我只能猜测是 decoder 这部分的参数配置有问题, 少什么参数了导致模糊

2021-08-05 08:23 UTC, ldm0 commented
> @ldm0 本来是高清视频, 但是现在这个清晰度太差, 不太清楚需要设置什么参数, 在我不使用filter, 只处理 decode->encode的时候, 效果也是一样不清晰, 所以我只能猜测是 decoder 这部分的参数配置有问题, 少什么参数了导致模糊

清晰度的话，可以看看比特率设置是否正确？

2021-08-05 17:52 UTC, ldm0 requested changes
Thanks! A comment:

2021-08-05 17:52 UTC, ldm0 commented on src/avfilter/avfilter.rs
> +    pub fn get_filter(&mut self, name: &CStr) -> Result<Option<AVFilterContextMut>> {
Please change this function to return `Option<AVFilterContextMut>`.

2021-08-06 05:25 UTC, ldm0 approved these changes
LGTM!

2021-08-06 05:25 UTC, merged